language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - bash build.sh

deploy:
  # - provider: pages
  #   repo: diagnijmegen/website-base
  #   skip_cleanup: true
  #   keep_history: true
  #   local_dir: website-base/output
  #   target_brach: gh-pages
  #   email: webteamdiag@gmail.com
  #   name: "Webteam DIAG Deploy Bot"
  #   github_token: $GH_PAGES
  #   on:
  #     brach: master
  - provider: pages
    repo: diagnijmegen/website-retina
    skip_cleanup: true
    keep_history: true
    local_dir: website-retina/output
    target_brach: master
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github_token: $GH_PAGES
    on:
      brach: master
  - provider: pages
    repo: diagnijmegen/website-pathology
    skip_cleanup: true
    keep_history: true
    local_dir: website-pathology/output
    target_brach: gh-pages
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github_token: $GH_PAGES
    on:
      brach: master
    fqdn: www.computationalpathologygroup.eu
  - provider: pages
    repo: diagnijmegen/website-rse
    skip_cleanup: true
    keep_history: true
    local_dir: website-rse/output
    target_brach: master
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github_token: $GH_PAGES
    on:
      brach: master
