language: python
python:
  - "3.6"
git:
  depth: 1
branches:
  only:
    - master
cache:
  - pip
  - npm
install:
  - pip install -r requirements.txt
  - npm install --prefix imgoptim
script:
  - bash build.sh

deploy:
  - provider: pages
    repo: diagnijmegen/website-retina
    skip-cleanup: true
    keep-history: true
    local-dir: website-retina/output
    target-branch: master
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github-token: $GH_PAGES
    on:
      brach: master
    fqdn: www.a-eyeresearch.nl
  - provider: pages
    repo: diagnijmegen/website-pathology
    skip-cleanup: true
    keep-history: true
    local-dir: website-pathology/output
    target-branch: gh-pages
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github-token: $GH_PAGES
    on:
      brach: master
    fqdn: www.computationalpathologygroup.eu
  - provider: pages
    repo: diagnijmegen/website-rse
    skip-cleanup: true
    keep-history: true
    local-dir: website-rse/output
    target-branch: master
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github-token: $GH_PAGES
    on:
      brach: master
    fqdn: rse.diagnijmegen.nl
