language: python
python:
  - "3.6"
git:
  depth: 1
branches:
  only:
    - master
cache:
  - pip
  - npm
install:
  - pip install -r requirements.txt
  - npm install --prefix imgoptim
script:
  - bash build.sh

deploy:
  - provider: pages
    repo: diagnijmegen/website-msc-projects
    skip-cleanup: true
    keep-history: true
    local-dir: website-msc-projects/output
    target-branch: master
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github-token: $GH_PAGES
    on:
      brach: master
#     fqdn: diagnijmegen.github.io/website-msc-projects
  - provider: pages
    repo: diagnijmegen/website-retina
    skip-cleanup: true
    keep-history: true
    local-dir: website-retina/output
    target-branch: master
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github-token: $GH_PAGES
    on:
      brach: master
    fqdn: www.a-eyeresearch.nl
  - provider: pages
    repo: diagnijmegen/website-pathology
    skip-cleanup: true
    keep-history: true
    local-dir: website-pathology/output
    target-branch: gh-pages
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github-token: $GH_PAGES
    on:
      brach: master
    fqdn: www.computationalpathologygroup.eu
  - provider: pages
    repo: diagnijmegen/website-rse
    skip-cleanup: true
    keep-history: true
    local-dir: website-rse/output
    target-branch: master
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github-token: $GH_PAGES
    on:
      brach: master
    fqdn: rse.diagnijmegen.nl
  - provider: pages
    repo: diagnijmegen/website-bodyct
    skip-cleanup: true
    keep-history: true
    local-dir: website-bodyct/output
    target-branch: master
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github-token: $GH_PAGES
    on:
      brach: master
    fqdn: bodyct.diagnijmegen.nl
  - provider: pages
    repo: diagnijmegen/website-aiimnijmegen
    skip-cleanup: true
    keep-history: true
    local-dir: website-aiimnijmegen/output
    target-branch: master
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github-token: $GH_PAGES
    on:
      brach: master
    fqdn: aiimnijmegen.nl
  - provider: pages
    repo: diagnijmegen/website-neuro
    skip-cleanup: true
    keep-history: true
    local-dir: website-neuro/output
    target-branch: master
    email: webteamdiag@gmail.com
    name: "Webteam DIAG Deploy Bot"
    github-token: $GH_PAGES
    on:
      brach: master
notifications:
  email:
    recipients:
      - $WEBTEAM_EMAIL
    on_success: change # default: change
    on_failure: change # default: always
