# Default settings for all Pelican builds
build_defaults: &build_defaults
  stage: build and deploy
  language: python
  python: 3.6
  before_install:
    - export TZ=Europe/Amsterdam
  script:
    - bash parse_publications.sh
    - bash copy_content.sh
    - bash deploy.sh
  cache:
    - pip

# Default configuration for the deploy to Github Pages
deploy_defaults: &deploy_defaults
    provider: pages
    repo: diagnijmegen/$WEBSITE
    skip-cleanup: true
    keep_history: true
    local_dir: $WEBSITE/output
    target_branch: master
    email: $WEBTEAM_EMAIL
    name: "Webteam DIAG Deploy Bot"
    token: $GH_PAGES
    "on":
      branch: master

notifications:
  email:
    recipients:
      - $WEBTEAM_EMAIL
    on_success: change # default: change
    on_failure: always # default: always

jobs:
  include:
    # Build and deploy steps for Pathology website
    - <<: *build_defaults
      name: Build Computational Pathology website
      env:
        - WEBSITE=website-pathology
        - GENERATE_PUB=1
      deploy:
        <<: *deploy_defaults
        fqdn: www.computationalpathologygroup.eu
    # Build and deploy steps for Retina website
    - <<: *build_defaults
      name: Build Retina website
      env:
        - WEBSITE=website-retina
        - GENERATE_PUB=1
      deploy:
        <<: *deploy_defaults
        fqdn: www.a-eyeresearch.nl
    # Build and deploy steps for RSE website
    - <<: *build_defaults
      name: Build RSE website
      env:
        - WEBSITE=website-rse
        - GENERATE_PUB=1
      deploy:
        <<: *deploy_defaults
        fqdn: rse.diagnijmegen.nl
    # Build and deploy steps for AIIM website
    - <<: *build_defaults
      name: Build AIIM website
      env:
        - WEBSITE=website-aiimnijmegen
        - GENERATE_PUB=1
      deploy:
        <<: *deploy_defaults
        fqdn: www.aiimnijmegen.nl
    # Build and deploy steps for Bodyct website
    # - <<: *build_defaults
    #   name: Build BodyCT website
    #   env:
    #     - WEBSITE=website-bodyct
    #     - GENERATE_PUB=1
    #   deploy:
    #     <<: *deploy_defaults
    #     fqdn: bodyct.diagnijmegen.nl
    # Build and deploy steps for Neuro website
    - <<: *build_defaults
      name: Build Neuro website
      env:
        - WEBSITE=website-neuro
        - GENERATE_PUB=1
      deploy:
        <<: *deploy_defaults
    # Beta deploy job for deploying to Netlify
    - <<: *build_defaults
      name: Build DIAG websites (Netlify beta)
      env:
        - WEBSITE=website-diag
        - GENERATE_PUB=1
        - SKIP_IMG_COPY=1
      deploy:
        provider: netlify
        site: $NETLIFY_SITEID_DIAG
        auth: $NETLIFY_AUTH
        edge: true # opt in to dpl v2
        dir: $WEBSITE/output
        prod: true
        on:
          branch: master
    # Build and deploy steps for RTC website
    - <<: *build_defaults
      name: Build RTC website
      env:
        - WEBSITE=website-rtc
        - GENERATE_PUB=1
      deploy:
        <<: *deploy_defaults
        fqdn: rtc.diagnijmegen.nl
    # Build and deploy steps for AI-for-Health website
    - <<: *build_defaults
      name: Build AI-for-Health website
      env:
        - WEBSITE=website-ai-for-health
        - GENERATE_PUB=0
      deploy:
        <<: *deploy_defaults
        fqdn: www.ai-for-health.nl
    # Run image optimization script
    - stage: images
      if: branch = master
      script: bash ./optimize_images.sh
      language: node_js
      node_js: 10.15
      install:
        - npm install --prefix imgoptim --no-save
      cache:
        - npm
      # Beta deploy media to Netlify
      deploy:
        provider: netlify
        site: $NETLIFY_SITEID_MEDIA
        auth: $NETLIFY_AUTH
        edge: true # opt in to dpl v2
        dir: assets_deploy
        prod: true
        on:
          branch: master
