# Default settings for all Pelican builds
_build_defaults: &build_defaults
  stage: build and deploy
  language: python
  python: 3.6
  before_install:
    - export TZ=Europe/Amsterdam
  script:
    - bash parse_publications.sh
    - bash copy_content.sh
    - bash deploy.sh
  cache:
    - pip
  if: branch = master

# Default configuration for the deploy to Github Pages
_deploy_defaults: &deploy_defaults
    provider: pages
    repo: diagnijmegen/$WEBSITE
    skip_cleanup: true
    keep_history: true
    local_dir: $WEBSITE/output
    target_branch: master
    email: $WEBTEAM_EMAIL
    name: "Webteam DIAG Deploy Bot"
    token: $GH_PAGES
    "on":
      branch: master

# Default configuration for deploys to Netlify
_netlify_deploy_defaults: &netlify_deploy_defaults
    provider: netlify
    auth: $NETLIFY_AUTH
    edge: true # opt in to dpl v2
    dir: $WEBSITE/output
    prod: true
    "on":
      branch: master

# Default configuration for dev deploys to Netlify
_netlify_dev_deploy_defaults: &netlify_dev_deploy_defaults
    provider: netlify
    auth: $NETLIFY_DEV_AUTH
    edge: true # opt in to dpl v2
    dir: $WEBSITE/output
    prod: true
    "on":
      branch: develop

notifications:
  email:
    recipients:
      - $WEBTEAM_EMAIL
    on_success: change # default: change
    on_failure: always # default: always

jobs:
  include:
    # Build and deploy steps for Pathology website
    - <<: *build_defaults
      name: Build Computational Pathology website
      env:
        - WEBSITE=website-pathology
        - GENERATE_PUB=1
      deploy:
        <<: *netlify_deploy_defaults
        site: $NETLIFY_SITEID_PATHOLOGY
    # Build and deploy steps for Retina website
    - <<: *build_defaults
      name: Build Retina website
      env:
        - WEBSITE=website-retina
        - GENERATE_PUB=1
      deploy:
        <<: *netlify_deploy_defaults
        site: $NETLIFY_SITEID_RETINA
    # Build and deploy steps for RSE website
    - <<: *build_defaults
      name: Build RSE website
      env:
        - WEBSITE=website-rse
        - GENERATE_PUB=1
      deploy:
        <<: *deploy_defaults
        fqdn: rse.diagnijmegen.nl
    # Build and deploy steps for AIIM website
    - <<: *build_defaults
      name: Build AIIM website
      env:
        - WEBSITE=website-aiimnijmegen
        - GENERATE_PUB=1
      deploy:
        <<: *deploy_defaults
        fqdn: www.aiimnijmegen.nl
    # Deploy job for deploying to Netlify
    - <<: *build_defaults
      name: Build DIAG website
      env:
        - WEBSITE=website-diag
        - GENERATE_PUB=1
      deploy:
        <<: *netlify_deploy_defaults
        site: $NETLIFY_SITEID_DIAG

    - <<: *build_defaults
      name: Build DIAG website (dev branch)
      if: branch = develop
      env:
        - WEBSITE=website-diag
        - GENERATE_PUB=1
        - DEVELOPMENT=1
      deploy:
        <<: *netlify_dev_deploy_defaults
        site: $NETLIFY_SITEID_DIAG_BETA

    # Build and deploy steps for RTC website
    - <<: *build_defaults
      name: Build RTC website
      env:
        - WEBSITE=website-rtc
        - GENERATE_PUB=1
      deploy:
        <<: *deploy_defaults
        fqdn: rtc.diagnijmegen.nl
    # Build and deploy steps for AI-for-Health website
    - <<: *build_defaults
      name: Build AI-for-Health website
      env:
        - WEBSITE=website-ai-for-health
        - GENERATE_PUB=0
      deploy:
        <<: *netlify_deploy_defaults
        site: $NETLIFY_SITEID_AIFORHEALTH
    # Run image optimization script
    - stage: images
      if: branch = master
      script: bash ./optimize_images.sh
      language: node_js
      node_js: 10.15
      install:
        - npm install --prefix imgoptim --no-save
      cache:
        - npm
      # Beta deploy media to Netlify
      deploy:
        provider: netlify
        site: $NETLIFY_SITEID_MEDIA
        auth: $NETLIFY_AUTH
        edge: true # opt in to dpl v2
        dir: assets
        prod: true
        on:
          branch: master
