name: "Build and Deploy"
description: "This will buid"
# inputs:
#   website-dir: # id of input
#     description: "Website to build"
#     required: true
#     default: ""
#   website-api: # id of input
#     description: "Website Api"
#     required: true
#     default: ""
#   netlify_key: # id of input
#     description: "Netlify Key"
#     required: true
#     default: ""

# outputs:
#   random-number:
#     description: "Random number"
#     value: hello

runs:
  using: "composite"
  steps:
    - name: Echo run
      run: echo ${{ matrix.run-on-branch }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - uses: actions/cache@v2
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
    - name: Install dependencies
      if: ${{ github.ref ==  matrix.run-on-branch  && steps.cache.outputs.cache-hit != 'true' }}
      run: |
        pip install -r ./requirements.txt
    - name: Parse Publications
      run: bash ./parse_publications.sh
    - name: Copy Content
      run: bash copy_content.sh
      env:
        WEBSITE: ${{ matrix.website-dir }}
    - name: Deploy Settings
      run: bash deploy.sh
      env:
        WEBSITE: ${{ matrix.website-dir }}
        DEVELOPMENT: 1
    - name: Netlify deploy
      run: |
        yarn global add netlify-cli
        "$(yarn global bin)/netlify" deploy --dir=${{ matrix.website-dir }}/output --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEV_AUTH }}
        NETLIFY_SITE_ID: ${{ secrets[matrix.site-id] }}
