name: "Build and Deploy"
description: "This will buid"
inputs:
  website-dir: # id of input
    description: "Website to build"
    required: true
    default: ""
  website-api: # id of input
    description: "Website Api"
    required: true
    default: ""
  netlify_key: # id of input
    description: "Netlify Key"
    required: true
    default: ""

  development: # id of input
    description: "development"
    required: false
    default: 0

runs:
  using: "composite"
  steps:
    - name: Copy Content
      run: bash copy_content.sh
      shell: bash
      env:
        WEBSITE: ${{ inputs.website-dir }}
    - name: Deploy Settings
      run: bash deploy.sh
      shell: bash
      env:
        WEBSITE: ${{ inputs.website-dir }}
        DEVELOPMENT: ${{ inputs.development }}
    - name: Netlify deploy
      run: |
        yarn global add netlify-cli
        "$(yarn global bin)/netlify" deploy --dir=${{ inputs.website-dir }}/output --prod
      shell: bash
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.netlify_key }}
        NETLIFY_SITE_ID: ${{ inputs.website-api }}
