#[[redirects]]
#  from = "/projects"
#  to = "/research"
#  status = 301
#  force = true

[[redirects]]
  from = "/highlights/:title/"
  to = "/news/:title/"
  status = 301
  force = true

[[redirects]]
  from = "/highlights/"
  to = "/news/"
  status = 301
  force = true