#[[redirects]]
#  from = "/projects"
#  to = "/research"
#  status = 301
#  force = true

[[redirects]]
  from = "/highlights/:title/"
  to = "/news/:title/"
  status = 301

[[redirects]]
  from = "/highlights/"
  to = "/news/"
  status = 301

[[redirects]]
  from = "/index.php/Publication"
  query = {bibkey = ":bibkey"}
  to = "/publications/:bibkey/"
  status = 301

[[redirects]]
  from = "/index.php/Publications"
  to = "/publications/"
  status = 301

[[redirects]]
  from = "/index.php/Research"
  to = "/research/"
  status = 301
  
[[redirects]]
  from = "/index.php/Theses"
  to = "/thesis-gallery/"
  status = 301

[[redirects]]
  from = "/index.php/Vacancies"
  to = "/vacancies/"
  status = 301

[[redirects]]
  from = "/index.php/MasterProjects"
  to = "/vacancies/"
  status = 301
  
[[redirects]]
  from = "/index.php/Contact"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/index.php/About"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/index.php/Digital_Pathology"
  to = "/research/pathology/"
  status = 301

[[redirects]]
  from = "/index.php/Neuro"
  to = "/research/neuro/"
  status = 301

[[redirects]]
  from = "/index.php/Retina"
  to = "/research/retina/"
  status = 301

[[redirects]]
  from = "/index.php/Chest"
  to = "/research/cxr/"
  status = 301

[[redirects]]
  from = "/index.php/Breast"
  to = "/research/breast-image-analysis/"
  status = 301

[[redirects]]
  from = "/index.php/Prostate"
  to = "/research/pelvic/"
  status = 301

# People redirects
#
#
#

[[redirects]]
  from = "index.php/Person?name=Bram_van_Ginneken"
  to = "/people/bram-van-ginneken/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Nico_Karssemeijer"
  to = "/people/nico-karssemeijer/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Francesco_Ciompi"
  to = "/people/francesco-ciompi/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Henkjan_Huisman"
  to = "/people/henkjan-huisman/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Colin_Jacobs"
  to = "/people/colin-jacobs/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Jeroen_van_der_Laak"
  to = "/people/jeroen-van-der-laak/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Geert_Litjens"
  to = "/people/geert-litjens/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Rashindra_Manniesing"
  to = "/people/rashindra-manniesing/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=James_Meakin"
  to = "/people/james-meakin/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Matthieu_Rutten"
  to = "/people/matthieu-rutten/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Clarisa_S%C3%A1nchez"
  to = "/people/clarisa-sanchez/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Cornelia_Schaefer-Prokop"
  to = "/people/cornelia-schaefer-prokop/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Witali_Aswolinskiy"
  to = "/people/witali-aswolinskiy/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Thomas_van_den_Heuvel"
  to = "/people/thomas-van-den-heuvel/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Nikolas_Lessmann"
  to = "/people/nikolas-lessmann/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Caner_Mercan"
  to = "/people/caner-mercan/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Nikita_Moriakov"
  to = "/people/nikita-moriakov/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Keelin_Murphy"
  to = "/people/keelin-murphy/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Steven_Schalekamp"
  to = "/people/steven-schalekamp/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Ernst_Scholten"
  to = "/people/ernst-scholten/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Jonas_Teuwen"
  to = "/people/jonas-teuwen/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Elke_Loskamp-Huntink"
  to = "/people/elke-loskamp-huntink/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Rita_Bijlsma"
  to = "/people/rita-bijlsma/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Merijn_van_Erp"
  to = "/people/merijn-van-erp/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Paul_Konstantin_Gerke"
  to = "/people/paul-konstantin-gerke/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Miriam_Groeneveld"
  to = "/people/miriam-groeneveld/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Sjoerd_Kerkstra"
  to = "/people/sjoerd-kerkstra/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Sil_van_de_Leemput"
  to = "/people/sil-van-de-leemput/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Mike_Overkamp"
  to = "/people/mike-overkamp/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Maud_Wekking"
  to = "/people/maud-wekking/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Harm_van_Zeeland"
  to = "/people/harm-van-zeeland/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Alessandro_Ardu"
  to = "/people/alessandro-ardu/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Maschenka_Balkenhol"
  to = "/people/maschenka-balkenhol/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=P%C3%A9ter_B%C3%A1ndi"
  to = "/people/peter-bandi/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Thomas_de_Bel"
  to = "/people/thomas-de-bel/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=John-Melle_Bokhorst"
  to = "/people/john-melle-bokhorst/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Luuk_Boulogne"
  to = "/people/luuk-boulogne/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Patrick_Brand"
  to = "/people/patrick-brand/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Wouter_Bulten"
  to = "/people/wouter-bulten/"
  query = {name = ":name"}
  status = 301
[[redirects]]
  from = "index.php/Person?name=Erdi_Calli"
  to = "/people/erdi-calli/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Oscar_Debats"
  to = "/people/oscar-debats/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Koen_Dercksen"
  to = "/people/koen-dercksen/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Miguel_Fernandes"
  to = "/people/miguel-fernandes/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Daan_Geijs"
  to = "/people/daan-geijs/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Cristina_Gonzalez_Gonzalo"
  to = "/people/cristina-gonzalez-gonzalo/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Jasper_van_der_Graaf"
  to = "/people/jasper-van-der-graaf/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Tariq_Haddad"
  to = "/people/tariq-haddad/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Ward_Hendrix"
  to = "/people/ward-hendrix/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Meyke_Hermsen"
  to = "/people/meyke-hermsen/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Matin_Hosseinzadeh"
  to = "/people/matin-hosseinzadeh/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Gabriel_Humpire_Mamani"
  to = "/people/gabriel-humpire-mamani/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Michel_Kok"
  to = "/people/michel-kok/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Kevin_Koschmieder"
  to = "/people/kevin-koschmieder/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Kicky_van_Leeuwen"
  to = "/people/kicky-van-leeuwen/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Bart_Liefers"
  to = "/people/bart-liefers/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Jasper_Linmans"
  to = "/people/jasper-linmans/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Esther_Markus-Smeets"
  to = "/people/esther-markus-smeets/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Midas_Meijs"
  to = "/people/midas-meijs/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Ajay_Patel"
  to = "/people/ajay-patel/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Hans_Pinckaers"
  to = "/people/hans-pinckaers/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Sarah_van_Riel"
  to = "/people/sarah-van-riel/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Mart_van_Rijthoven"
  to = "/people/mart-van-rijthoven/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Riccardo_Samperna"
  to = "/people/riccardo-samperna/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Anton_Schreuder"
  to = "/people/anton-schreuder/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Cheryl_Sital"
  to = "/people/cheryl-sital/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Ecem_Sogancioglu"
  to = "/people/ecem-sogancioglu/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=David_Tellez"
  to = "/people/david-tellez/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Kiran_Vaidhya_Venkadesh"
  to = "/people/kiran-vaidhya-venkadesh/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Coen_de_Vente"
  to = "/people/coen-de-vente/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Xie_Weiyi"
  to = "/people/xie-weiyi/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Gaby_Whitehead"
  to = "/people/gaby-whitehead/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Bram_de_Wilde"
  to = "/people/bram-de-wilde/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Ludo_van_Alst"
  to = "/people/ludo-van-alst/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Niels_van_den_Hork"
  to = "/people/niels-van-den-hork/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Thijs_van_den_Hout"
  to = "/people/thijs-van-den-hout/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Jeffrey_Hoven"
  to = "/people/jeffrey-hoven/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Ruben_Kluge"
  to = "/people/ruben-kluge/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Chase_Neff"
  to = "/people/chase-neff/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Martijn_Schilpzand"
  to = "/people/martijn-schilpzand/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Rens_van_Schouwenburg"
  to = "/people/rens-van-schouwenburg/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Grzegorz_Chlebus"
  to = "/people/grzegorz-chlebus/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Nils_Hendrix"
  to = "/people/nils-hendrix/"
  status = 301
[[redirects]]
  from = "index.php/Person?name=Alessa_Hering"
  to = "/people/alessa-hering/"
  status = 301