#[[redirects]]
#  from = "/projects"
#  to = "/research"
#  status = 301
#  force = true

[[redirects]]
  from = "/highlights/:title/"
  to = "/news/:title/"
  status = 301

[[redirects]]
  from = "/highlights/"
  to = "/news/"
  status = 301

[[redirects]]
  from = "/index.php/Publication"
  query = {bibkey = ":bibkey"}
  to = "/publications/:bibkey/"
  status = 301

[[redirects]]
  from = "/index.php/Publications"
  to = "/publications/"
  status = 301

