name: Build and Deploy (Develop)

on:
  push:
    branches: develop

jobs:
  deploy:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - name: website-diag
            site-id: NETLIFY_SITEID_DIAG_BETA

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Build and Deploy
        uses: ./.github/workflows/actions/build-and-deploy
        with:
          website-dir: ${{ matrix.name }}
          website-api: ${{ secrets[matrix.site-id] }}
          netlify_key: ${{ secrets.NETLIFY_DEV_AUTH }}
          github_token: ${{ secrets.GH_BIB_TOKEN }}
          development: 1
