# name: Deploy and Publish

# on:
#   push:
#     branches: master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         include:
#           - website-dir: website-pathology
#             site-id: NETLIFY_SITEID_PATHOLOGY
#           - website-dir: website-retina
#             site-id: NETLIFY_SITEID_RETINA

#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v1
#         with:
#           python-version: 3.6

#       - name: Install dependencies
#         run: pip install -r ./requirements.txt

#       - name: Parse Publications
#         run: bash ./parse_publications.sh

#       - name: Copy Content
#         run: bash copy_content.sh
#         env:
#           WEBSITE: ${{ matrix.website-dir }}

#       - name: Deploy Settings
#         run: bash deploy.sh
#         env:
#           WEBSITE: ${{ matrix.website-dir }}
#           DEVELOPMENT: 0

#       - name: Publish
#         uses: netlify/actions/cli@master
#         env:
#           NETLIFY_SITE_ID: ${{ secrets[matrix.site-id] }}
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEV_AUTH }}
#         with:
#           args: deploy --dir=${{ matrix.website-dir }}/output --prod

#   images:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: "10.15"

#       - name: Setup npm
#         run: npm install --prefix imgoptim --no-save

#       - name: Optimize
#         run: bash ./optimize_images.sh

#       - name: Publish
#         uses: netlify/actions/cli@master
#         env:
#           NETLIFY_SITE_ID: ${{ secrets. $NETLIFY_SITEID_MEDIA }}
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEV_AUTH }}
#         with:
#           args: deploy --dir=assets --prod

