name: Deploy and Publish develop test

on:
  push:
    branches: develop

    jobs:
      # deploy:
      #   runs-on: ubuntu-latest
      #   steps:
      #     - uses: actions/checkout@v2

      #     - name: Setup python
      #       uses: actions/setup-python@v1
      #       with:
      #         python-version: 3.6

      #     - name: Install dependencies
      #       run: pip install -r ./requirements.txt

      #     - name: Parse Publications
      #       run: bash ./parse_publications.sh

      #     - name: Copy Content
      #       run: bash copy_content.sh
      #       env:
      #         WEBSITE: website-diag
      #         DEVELOPMENT: 1

      #     - name: Deploy Settings
      #       run: bash deploy.sh
      #       env:
      #         WEBSITE: website-diag
      #         DEVELOPMENT: 1

      #     - name: Publish
      #       uses: netlify/actions/cli@master
      #       env:
      #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITEID_DIAG_BETA }}
      #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEV_AUTH }}
      #       with:
      #         args: deploy --dir=website-diag/output --prod

      images:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - name: Setup npm
            uses: actions/setup-node@v1
            run: npm install --prefix imgoptim --no-save
            with:
              node-version: "10.15"

          - name: Optimize
            run: bash ./optimize_images.sh
