name: Build and Deploy (Develop)

on:
  push:
    branches: develop
jobs:
  deploy:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - website-dir: website-diag
            site-id: NETLIFY_SITEID_DIAG_BETA
            run-on-branch: refs/heads/develop

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
      - name: Install dependencies
        if: ${{ github.ref ==  matrix.run-on-branch  && steps.cache.outputs.cache-hit != 'true' }}
        run: |
          pip install -r ./requirements.txt
      - name: Use local my-action
        uses: ./.github/workflows/actions/build-and-deploy
        with:
          website-dir: ${{ matrix.website-dir }}
          website-api: ${{ secrets[matrix.site-id] }}
          netlify_key: ${{ secrets.NETLIFY_DEV_AUTH }}
          github_token: ${{ secrets.GH_BIB_TOKEN }}
          development: 1
