name: Optimize Images
on:
  push:
    branches: master
    paths:
      - "content/images/**"

jobs:
  images:
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.17"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup npm
        run: npm install --prefix imgoptim --no-save
      - name: Optimize
        run: bash ./optimize_images.sh

      - name: Deploy images to Netlify
        run: |
          yarn global add netlify-cli
          "$(yarn global bin)/netlify" deploy --dir=assets --prod
        shell: bash
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEV_AUTH }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITEID_MEDIA }}
