name: Optimize Images
on:
  push:
    branches: [master]
    # paths:
    #   - "content/images/**"

jobs:
  cancel-running-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  images:
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.17"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup npm
        run: npm install --prefix imgoptim --no-save

      - name: Optimize Images
        run: |
          cd imgoptim
          node optimize.js
          cd ..

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update optimized images
          file_pattern: imgoptim/image-cache.json assets/images/*

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Netlify
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn global add netlify-cli

      - name: Deploy images to Netlify
        run: |
          cp -r --no-clobber ./content/images/. assets/images
          "$(yarn global bin)/netlify" deploy --dir=assets --prod
        shell: bash
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEV_AUTH }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITEID_MEDIA }}
